// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBydfcHgvAQvMJv-fIv4c5DeaDkIeZZ0kE',
    appId: '1:883431216013:web:02cf490f70b21e315de3c4',
    messagingSenderId: '883431216013',
    projectId: 'multiplatform-todolist',
    authDomain: 'multiplatform-todolist.firebaseapp.com',
    storageBucket: 'multiplatform-todolist.firebasestorage.app',
    measurementId: 'G-PJ76RLNPDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cmS20LXgYfyjVEGIcxRfvXGQRmySzfQ',
    appId: '1:883431216013:android:55eb398929984cfa5de3c4',
    messagingSenderId: '883431216013',
    projectId: 'multiplatform-todolist',
    storageBucket: 'multiplatform-todolist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrysqbj90R4slvdT57cNQZWanraPTOsPE',
    appId: '1:883431216013:ios:f698b6736c02befd5de3c4',
    messagingSenderId: '883431216013',
    projectId: 'multiplatform-todolist',
    storageBucket: 'multiplatform-todolist.firebasestorage.app',
    iosBundleId: 'com.example.tooDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrysqbj90R4slvdT57cNQZWanraPTOsPE',
    appId: '1:883431216013:ios:f698b6736c02befd5de3c4',
    messagingSenderId: '883431216013',
    projectId: 'multiplatform-todolist',
    storageBucket: 'multiplatform-todolist.firebasestorage.app',
    iosBundleId: 'com.example.tooDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBydfcHgvAQvMJv-fIv4c5DeaDkIeZZ0kE',
    appId: '1:883431216013:web:0fcbdcf16a01e7d75de3c4',
    messagingSenderId: '883431216013',
    projectId: 'multiplatform-todolist',
    authDomain: 'multiplatform-todolist.firebaseapp.com',
    storageBucket: 'multiplatform-todolist.firebasestorage.app',
    measurementId: 'G-XYBH1MHDPW',
  );
}
